server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuraciones #Esto es la ruta donde van a estar las configuraciones de todos los microservicios

management:
  endpoints:
    web:
      exposure:
        include: health,info