INSERT IGNORE INTO `rios` (`id`, `descripcion`, `imagen`, `nombre`) VALUES
(1, 'El río Duero es el cuerpo de agua dulce con mayor caudal de la península ibérica, incluyendo España y Portugal. Además, es el tercer río más largo de España y el más importante del noroeste del país. Discurre por las provincias españolas de Burgos, Salamanca, Soria, Valladolid y Zamora; y los distritos portugueses de Aveiro, Braganza, Guarda, Oporto, Vila Real y Viseo.\n\nPosee una longitud de 897 kilómetros, un caudal medio de 800 m³/s y una cuenca hidrográfica que ocupa cerca de 98.073 km². Su nacimiento se ubica a 2.160 msnm en los Picos de Urbión del municipio español Duruelo de la Sierra, en la provincia de Soria; y su desembocadura se encuentra en el océano Atlántico, entre los municipios portugueses de Oporto y Vila Nova de Gaia.', 'https://cdn0.geoenciclopedia.com/es/posts/4/9/5/rio_duero_594_orig.jpg', 'Río Duero'),
(2, 'Es el segundo río más largo y caudaloso de España y la península ibérica, si hablamos de ríos que solo fluyen por España y no por Portugal, entonces el río Ebro es el río más caudaloso. Fluye a través de las provincias de Álava, Burgos, Cantabria, La Rioja, Lleida, Navarra, Palencia, Tarragona y Zaragoza; pertenecientes a las comunidades autónomas de Aragón, Cantabria, Castilla y León, Cataluña, La Rioja, Navarra y País Vasco.\n\nTiene un caudal medio de 600 m³/s, una longitud de 930 kilómetros y una cuenca hidrográfica que ocupa cerca de 86.100 km². Su fuente se ubica a 1.850 msnm en el pico Tres Mares de la cordillera Cantábrica, entre las provincias de Cantabria y Palencia.', 'https://theobjective.com/wp-content/uploads/2024/10/rio-Ebro.jpg', 'Río Ebro'),
(3, 'El río Guadiana es un cuerpo de agua dulce del sudoeste de la península ibérica que discurre por las comunidades autónomas españolas de Andalucía, Castilla-La Mancha y Extremadura y las regiones tradicionales portuguesas de Alentejo y Algarve.\n\nPosee una longitud de aproximadamente 818 kilómetros, una cuenca hidrográfica que ocupa 67.733 km² y un caudal medio que varía entre 26 m³/s y 78 m³/s. En un tramo mayor a 100 kilómetros, el río actúa como frontera natural entre España y Portugal. Cerca del 80% de su cuenca pertenece a territorio español y el 20% restante a territorio portugués.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/BA-Guadiana_internacional_04.jpg/640px-BA-Guadiana_internacional_04.jpg', 'Río Guadiana'),
(4, 'El Tajo es el río más largo de toda la península ibérica. En los más de mil kilómetros que recorre en su trayecto hasta el océano Atlántico, atraviesa cuatro comunidades autónomas españolas y cuatro distritos portugueses. Es un cuerpo de agua vital para muchas especies de flora y fauna endémica y en peligro de extinción. También es indispensable para todas las ciudades y poblados por los que transcurre porque sus aguas son utilizadas para generar energía hidroeléctrica, regar cultivos, abastecer a la industria ganadera y surtir incontables establecimientos y hogares.', 'https://turismotajointernacional.es/wp-content/uploads/2021/04/Rio-Tajo-Herrera-de-Alcantara-_DSC6729.jpg', 'Río tajo');

INSERT IGNORE INTO `rios_entity_pezid` (`rios_entity_id`, `pezid`) VALUES
(1, 1),
(1, 2),
(2, 3);