server:
  port: 8083

spring:
  application:
    name: msvc-voluntarios
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/voluntariosdb
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

admin:
  email: riverspainproyecto@gmail.com

springdoc:
  swagger-ui:
    path: /swagger-ui.html